### ISSUE TITLE
Formulaire d'inscription

### ISSUE THREAD

**Issue by Ahama-Jonathan** [JackJosue517/sirius#3]
Après confirmation du mot de passe les labels recouvrent les saisies des champs de mot de passe et le contenu ne redevient visible que si l'on fait une modification de valeur distinguant les mots de passe.

**Comment by JackJosue517** [comment]
Peux-tu envoyer une capture ?

**Comment by Ahama-Jonathan** [comment]
J'ai envoyé une vidéo sur WhatsApp

**Comment by JackJosue517** [comment]
Des alertes de sécurité ont été détectés.
Mettre à jour des dépendances.

**Comment by JackJosue517** [comment]
Hi. 🔆 
Bonne nouvelle, le bug a été résolu. 💯 
J'ai juste déplacé le code source relatif aux icônes check et tout a fonctionné parfaitement... 👍 
J'ai également profité pour retoucher aussi le fonds et la forme. Consulte le GIT LOG pour voir les modifications que j'ai eu à faire 😃 

Après check, si cela ne correspondait pas à l'issue, tu peux ré-ouvrir cette issue.

Keep Going 📁
